name: CI

on:
  push:
    branches:
     - master
    tags:
      - '*'
  pull_request:
    branches:
     - master
  schedule:
    - cron: '0 7 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - 7.2
          - 7.4
        typo3:
          - ^9.5
          - ^8.7

    steps:
      - uses: actions/checkout@v2

      - name: Build
        env:
          PHP_VERSION: ${{matrix.php}}
          TYPO3_VERSION: ${{matrix.typo3}}
        run: docker-compose run --rm app composer build

      - name: Cleanup
        if: ${{ always() }}
        run: docker-compose down --volumes

  release-ter:
    name: TYPO3 TER release

    if: startsWith(github.ref, 'refs/tags/')
    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to TER
        env:
          TYPO3_API_USERNAME: ${{secrets.TYPO3_API_USERNAME}}
          TYPO3_API_PASSWORD: ${{secrets.TYPO3_API_PASSWORD}}
        run: docker-compose run --rm app composer deploy:ter
